<?php

if (!defined('ABSPATH')) {
    exit;
}

// OPTIONS PAGES
if (function_exists('acf_add_options_page')) {

    acf_add_options_page(array(
        'page_title'    => 'AIC Settings',
        'menu_title'    => 'AIC Settings',
        'menu_slug'     => 'aic-general-settings',
        'capability'    => 'edit_posts',
        'icon_url'      => 'dashicons-edit-large',
        'redirect'      => false
    ));

    acf_add_options_sub_page(array(
        'page_title'     => 'Featured Casino',
        'menu_title'    => 'Featured Casino',
        'parent_slug'    => 'aic-general-settings',
    ));
}
// OPTIONS PAGES END

if (function_exists('acf_add_local_field_group')) :

    acf_add_local_field_group(array(
        'key' => 'group_5f05bddf850fc',
        'title' => 'AIC Casino Reviews',
        'fields' => array(
            array(
                'key' => 'field_5f1febd1d3aad',
                'label' => 'REDIRECT and T&C',
                'name' => '',
                'type' => 'accordion',
                'instructions' => 'Redirect link and terms of conditions text(if needed)',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'open' => 1,
                'multi_expand' => 0,
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f104d8ba0d4f',
                'label' => 'Review redirect',
                'name' => 'review_redirect',
                'type' => 'text',
                'instructions' => 'Enter casino review redirect link. For example /go/casino',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f1ff20e91e9e',
                'label' => 'Enable T&C',
                'name' => 'review_enable_tnc',
                'type' => 'true_false',
                'instructions' => 'Enable or disable terms and conditions',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Enable',
                'ui_off_text' => 'Disable',
            ),
            array(
                'key' => 'field_5f0827c668645',
                'label' => 'T&C\'s',
                'name' => 'review_terms',
                'type' => 'text',
                'instructions' => 'Terms and conditions for casino',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5f1ff20e91e9e',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f0712d3cd8dd',
                'label' => 'TOPLIST',
                'name' => '',
                'type' => 'accordion',
                'instructions' => 'Information about bonuses, withdraw methods, deposit methods etc. witch will be displayed in the [casino_review_list] shortcode',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'open' => 1,
                'multi_expand' => 0,
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f10642df42cf',
                'label' => 'Color',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f1063f5f42ce',
                'label' => 'Logo background',
                'name' => 'review_bg_color',
                'type' => 'color_picker',
                'instructions' => 'Select a color for logo background',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
            ),
            array(
                'key' => 'field_5f05bf6846c0d',
                'label' => 'Toplist Information',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f05c0e569f8a',
                'label' => 'Review bonus text first line',
                'name' => 'review_bonus_text_first_line',
                'type' => 'text',
                'instructions' => 'Bonus text first line. Will be bolded. For example €1,500 Bonus',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => 'This is placeholder text',
                'prepend' => '',
                'append' => '',
                'maxlength' => 82,
            ),
            array(
                'key' => 'field_5f05d4e281841',
                'label' => 'Review bonus text second line',
                'name' => 'review_bonus_text_second_line',
                'type' => 'text',
                'instructions' => 'Bonus text second line. Will be smaller. For example + 300 Free Spins',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f05d50681842',
                'label' => 'Review three pluses',
                'name' => 'review_casino_pluses',
                'type' => 'repeater',
                'instructions' => 'Enter up to three positive things about casino',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 3,
                'layout' => 'block',
                'button_label' => 'Add',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f05d587889c3',
                        'label' => 'Review Item',
                        'name' => 'review_item_field',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5f1fed934573f',
                'label' => 'Review three minuses',
                'name' => 'review_casino_minuses',
                'type' => 'repeater',
                'instructions' => 'Enter up to three casino minuses',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 3,
                'layout' => 'block',
                'button_label' => 'Add',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f1fed9345740',
                        'label' => 'Casino minus',
                        'name' => 'review_minus_item_field',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5f07004ac8730',
                'label' => 'More information tab',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f07013443e5f',
                'label' => 'More information tab',
                'name' => 'review_more_info_enable',
                'type' => 'true_false',
                'instructions' => 'Enable more information tab',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Active',
                'ui_off_text' => 'Disabled',
            ),
            array(
                'key' => 'field_5f072579a8b20',
                'label' => 'REVIEW PAGE',
                'name' => '',
                'type' => 'accordion',
                'instructions' => 'Information for single casino review page',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'open' => 0,
                'multi_expand' => 0,
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f1fe774c3cc2',
                'label' => 'Header table',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f07263af2b9d',
                'label' => 'Casino rating',
                'name' => 'review_rating',
                'type' => 'number',
                'instructions' => 'Enter casino rating. Rating up to 5 stars',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'min' => '',
                'max' => 5,
                'step' => '0.1',
            ),
            array(
                'key' => 'field_5f1fe79fc3cc3',
                'label' => 'Widthdrawal time',
                'name' => 'review_withdrawal_time',
                'type' => 'text',
                'instructions' => 'Enter withdrawal times for casino',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f1ab2e62aabb',
                'label' => 'Information field (sidebar)',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f1ab2f62aabc',
                'label' => 'Information field',
                'name' => 'review_bonus_information',
                'type' => 'repeater',
                'instructions' => 'Enter extra information. This will create table. Use icons from https://emojipedia.org/',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f1ab30d2aabd',
                        'label' => 'Label',
                        'name' => 'review_bonus_information_left',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                    array(
                        'key' => 'field_5f1ab7dd77679',
                        'label' => 'Text',
                        'name' => 'review_bonus_information_right',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
            array(
                'key' => 'field_5f1a9756b1e65',
                'label' => 'Payment methods / providers (sidebar)',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f070649190bf',
                'label' => 'Deposit methods',
                'name' => 'review_deposit_methods',
                'type' => 'checkbox',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'VISA' => 'VISA',
                    'mastercard' => 'mastercard',
                    'skrill' => 'skrill',
                    'neteller' => 'neteller',
                    'swedbank' => 'swedbank',
                    'SEB' => 'SEB',
                    'citadele' => 'citadele',
                    'nordea' => 'nordea',
                    'ecopayz' => 'ecopayz',
                    'bitcoin' => 'bitcoin',
                    'astropay' => 'astropay',
                    'trustly' => 'trustly',
                    'paysafe' => 'paysafe',
                    'apple pay' => 'apple pay',
                    'swish' => 'swish',
                    'paypal' => 'paypal',
                ),
                'allow_custom' => 1,
                'save_custom' => 1,
                'default_value' => array(),
                'layout' => 'horizontal',
                'toggle' => 0,
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5f0706f9f1777',
                'label' => 'Withdraw methods',
                'name' => 'review_withdraw_methods',
                'type' => 'checkbox',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'VISA' => 'VISA',
                    'mastercard' => 'mastercard',
                    'skrill' => 'skrill',
                    'neteller' => 'neteller',
                    'swedbank' => 'swedbank',
                    'SEB' => 'SEB',
                    'citadele' => 'citadele',
                    'nordea' => 'nordea',
                    'ecopayz' => 'ecopayz',
                    'bitcoin' => 'bitcoin',
                    'astropay' => 'astropay',
                    'trustly' => 'trustly',
                    'paysafe' => 'paysafe',
                    'apple pay' => 'apple pay',
                    'swish' => 'swish',
                    'paypal' => 'paypal',
                ),
                'allow_custom' => 1,
                'save_custom' => 1,
                'default_value' => array(),
                'layout' => 'horizontal',
                'toggle' => 0,
                'return_format' => 'value',
            ),
            array(
                'key' => 'field_5f22b48dc7e89',
                'label' => 'Providers',
                'name' => 'review_providers',
                'type' => 'checkbox',
                'instructions' => 'Enter casino providers',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'choices' => array(
                    'Microgaming' => 'Microgaming',
                    'Isoftbet' => 'Isoftbet',
                    'Nektan' => 'Nektan',
                    'Net Ent' => 'Net Ent',
                    'GiG' => 'GiG',
                    'Pragmatic' => 'Pragmatic',
                    'Play n Go' => 'Play n Go',
                    'Yggdrasil' => 'Yggdrasil',
                    'Quickspin' => 'Quickspin',
                    'Red Tiger' => 'Red Tiger',
                    'Scientific' => 'Scientific',
                    'ELK' => 'ELK',
                    'RabCat' => 'RabCat',
                    'Push Gaming' => 'Push Gaming',
                    'NYX Gaming' => 'NYX Gaming',
                    'Thunderkick' => 'Thunderkick',
                    'Playtech' => 'Playtech',
                    'Big Time Gaming' => 'Big Time Gaming',
                    'BetDigital Gaming' => 'BetDigital Gaming',
                    'StormCraft Studios' => 'StormCraft Studios',
                    'NextGen Gaming' => 'NextGen Gaming',
                    'Habanero Gaming' => 'Habanero Gaming',
                    'Evolution Gaming' => 'Evolution Gaming',
                    'Merkur Gaming' => 'Merkur Gaming',
                    'Amaya' => 'Amaya',
                    'Realtime Gaming' => 'Realtime Gaming',
                    'Cryptologic' => 'Cryptologic',
                    'IGT' => 'IGT',
                    'Novomatic' => 'Novomatic',
                    'Fugaso Gaming' => 'Fugaso Gaming',
                    'Aristocrat' => 'Aristocrat',
                    'WMS' => 'WMS',
                    'EGT' => 'EGT',
                    'Betsoft Gaming' => 'Betsoft Gaming',
                    'Exclusive' => 'Exclusive',
                ),
                'allow_custom' => 0,
                'default_value' => array(),
                'layout' => 'horizontal',
                'toggle' => 0,
                'return_format' => 'value',
                'save_custom' => 0,
            ),
            array(
                'key' => 'field_5f1aaca6ec191',
                'label' => 'Customer support (sidebar)',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f1aacc6ec192',
                'label' => 'Customer support information',
                'name' => 'review_customer_support',
                'type' => 'repeater',
                'instructions' => 'Information about customer support. For example: Email: mail@sample.com etc.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'collapsed' => '',
                'min' => 0,
                'max' => 0,
                'layout' => 'table',
                'button_label' => '',
                'sub_fields' => array(
                    array(
                        'key' => 'field_5f1aaff9ec193',
                        'label' => 'Text',
                        'name' => 'review_customer_support_item',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                        'maxlength' => '',
                    ),
                ),
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'casino-review',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5f043a37d09db',
        'title' => 'AIC Casino Slots',
        'fields' => array(
            array(
                'key' => 'field_5f043d0366707',
                'label' => 'Basic Information',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f043d1566708',
                'label' => 'Slot Publisher',
                'name' => 'slot_publisher',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f1037680a614',
                'label' => 'Button redirect',
                'name' => 'slot_redirect',
                'type' => 'text',
                'instructions' => 'Redirect on play for real money button. For example /go/casino',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f044108c36c4',
                'label' => 'Slot Information',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f04411bc36c5',
                'label' => 'Slot payout percentage',
                'name' => 'slot_payout_percentage',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f044133c36c6',
                'label' => 'Slot bet limits(per spin)',
                'name' => 'slot_bet_range',
                'type' => 'text',
                'instructions' => 'For example 0.01 - 0.05 £',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f04416fc36c7',
                'label' => 'Slot Paylines',
                'name' => 'slot_paylines',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f3f89cfbf7ac',
                'label' => 'Jackpot available?',
                'name' => 'slot_jackpot_available',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Yes',
                'ui_off_text' => 'No',
            ),
            array(
                'key' => 'field_5f1036db1f196',
                'label' => 'Iframe',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f1036f31f197',
                'label' => 'Slot iframe',
                'name' => 'slot_iframe',
                'type' => 'url',
                'instructions' => 'Add iframe URL to display in slot page',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => 'casino-slot',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5f0228af1171e',
        'title' => 'AIC Featured Casino',
        'fields' => array(
            array(
                'key' => 'field_5f212ff51c314',
                'label' => 'Enable Featured Casino',
                'name' => 'fc_enable',
                'type' => 'true_false',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Enable',
                'ui_off_text' => 'Disable',
            ),
            array(
                'key' => 'field_5f2135cb95421',
                'label' => 'Redirect',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5f212ff51c314',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f21359fca751',
                'label' => 'Redirect',
                'name' => 'fc_redirect',
                'type' => 'text',
                'instructions' => 'Enter redirect link. For example /go/casino',
                'required' => 1,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f0228d5b1e58',
                'label' => 'Image',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5f212ff51c314',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f0228b5b1e57',
                'label' => 'Featured casino image',
                'name' => 'fc_casino_image',
                'type' => 'image',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'return_format' => 'array',
                'preview_size' => 'thumbnail',
                'library' => 'all',
                'min_width' => '',
                'min_height' => '',
                'min_size' => '',
                'max_width' => '',
                'max_height' => '',
                'max_size' => '',
                'mime_types' => '',
            ),
            array(
                'key' => 'field_5f02d1254e93b',
                'label' => 'Description',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5f212ff51c314',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'top',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f02d1394e93c',
                'label' => 'Main text',
                'name' => 'fc_main_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f02d1534e93d',
                'label' => 'Sub text',
                'name' => 'fc_sub_text',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'acf-options-featured-casino',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5f215b10d2c61',
        'title' => 'AIC Plugin Settings',
        'fields' => array(
            array(
                'key' => 'field_5f78599f6a16e',
                'label' => 'General Settings',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f7859d96a16f',
                'label' => 'Disable Review Navigation',
                'name' => 'disable_reviews_navigation',
                'type' => 'true_false',
                'instructions' => 'Disable review navigation in review pages.',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Disabled',
                'ui_off_text' => 'Enabled',
            ),
            array(
                'key' => 'field_5f215b1a7f073',
                'label' => 'Disable reviews slug',
                'name' => 'disable_reviews_slug',
                'type' => 'true_false',
                'instructions' => 'Disables reviews slug. Remember to refresh/flush permalinks at <strong>Settings -> Permalinks -> Save Changes</strong>',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Disabled',
                'ui_off_text' => 'Enabled',
            ),
            array(
                'key' => 'field_5f272df02fde4',
                'label' => 'Schema',
                'name' => '',
                'type' => 'tab',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'placement' => 'left',
                'endpoint' => 0,
            ),
            array(
                'key' => 'field_5f2733f479b39',
                'label' => 'Enable Schema',
                'name' => 'enable_schema',
                'type' => 'true_false',
                'instructions' => 'Enable casino reviews schema',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'message' => '',
                'default_value' => 0,
                'ui' => 1,
                'ui_on_text' => 'Enable',
                'ui_off_text' => 'Disable',
            ),
            array(
                'key' => 'field_5f272e0a2fde5',
                'label' => 'Site/Author name',
                'name' => 'reviews_schema_name',
                'type' => 'text',
                'instructions' => 'Enter site name. For example - casinosite.com',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5f2733f479b39',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f272ebe2fde6',
                'label' => 'Site URL',
                'name' => 'reviews_schema_site_url',
                'type' => 'url',
                'instructions' => 'Enter site URL',
                'required' => 0,
                'conditional_logic' => array(
                    array(
                        array(
                            'field' => 'field_5f2733f479b39',
                            'operator' => '==',
                            'value' => '1',
                        ),
                    ),
                ),
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'options_page',
                    'operator' => '==',
                    'value' => 'aic-general-settings',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5f17f686c26ad',
        'title' => 'AIC Review Widget',
        'fields' => array(
            array(
                'key' => 'field_5f17f6b3fb149',
                'label' => 'Header',
                'name' => 'review_widget_header',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
            array(
                'key' => 'field_5f3ce682775a9',
                'label' => 'Reviews to show',
                'name' => 'review_widget_post_object',
                'type' => 'post_object',
                'instructions' => 'Choose casino reviews you want to show',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'post_type' => array(
                    0 => 'casino-review',
                ),
                'taxonomy' => '',
                'allow_null' => 0,
                'multiple' => 1,
                'return_format' => 'id',
                'ui' => 1,
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'widget',
                    'operator' => '==',
                    'value' => 'casino_review',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

    acf_add_local_field_group(array(
        'key' => 'group_5f0488c4f0ee0',
        'title' => 'AIC Slot Widget',
        'fields' => array(
            array(
                'key' => 'field_5f0488cb37cf1',
                'label' => 'Header',
                'name' => 'header',
                'type' => 'text',
                'instructions' => '',
                'required' => 0,
                'conditional_logic' => 0,
                'wrapper' => array(
                    'width' => '',
                    'class' => '',
                    'id' => '',
                ),
                'default_value' => '',
                'placeholder' => '',
                'prepend' => '',
                'append' => '',
                'maxlength' => '',
            ),
        ),
        'location' => array(
            array(
                array(
                    'param' => 'widget',
                    'operator' => '==',
                    'value' => 'casino_slot',
                ),
            ),
        ),
        'menu_order' => 0,
        'position' => 'normal',
        'style' => 'default',
        'label_placement' => 'top',
        'instruction_placement' => 'label',
        'hide_on_screen' => '',
        'active' => true,
        'description' => '',
    ));

endif;
